# Generated by Django 4.0.4 on 2022-04-11 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('tutor_skills', models.CharField(max_length=250, null=True)),
                ('tutor_exp', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
