# Generated by Django 4.0.4 on 2022-04-11 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=100)),
                ('course_description', models.CharField(max_length=250)),
                ('course_duration', models.IntegerField(blank=True, null=True)),
                ('tutor_id', models.ManyToManyField(related_name='tutor_id', to='tutor.tutor_info')),
            ],
        ),
    ]
