# Generated by Django 4.0.4 on 2022-04-11 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_info',
            name='tutor_id',
        ),
        migrations.AddField(
            model_name='course_info',
            name='tutor_id',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='tutor.tutor_info'),
            preserve_default=False,
        ),
    ]
